"""removed age cloumn from players

Revision ID: 01d1e5a42bfa
Revises: 6fee32ace2b7
Create Date: 2026-04-26 02:19:12.101005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d1e5a42bfa'
down_revision: Union[str, Sequence[str], None] = '6fee32ace2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_age'), table_name='players')
    op.drop_column('players', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_players_age'), 'players', ['age'], unique=False)
    # ### end Alembic commands ###
