"""add custom_players table

Revision ID: 12b528e6fccc
Revises: 89894c529cf9
Create Date: 2026-03-29 00:09:52.577885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b528e6fccc'
down_revision: Union[str, Sequence[str], None] = '89894c529cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=False),
    sa.Column('preferred_foot', sa.String(length=5), nullable=False),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('shooting', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('dribbling', sa.Integer(), nullable=False),
    sa.Column('defending', sa.Integer(), nullable=False),
    sa.Column('physic', sa.Integer(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.CheckConstraint("preferred_foot IN ('Left', 'Right')", name='ck_cp_foot'),
    sa.CheckConstraint('defending    BETWEEN 1 AND 99', name='ck_cp_defending'),
    sa.CheckConstraint('dribbling    BETWEEN 1 AND 99', name='ck_cp_dribbling'),
    sa.CheckConstraint('pace         BETWEEN 1 AND 99', name='ck_cp_pace'),
    sa.CheckConstraint('passing      BETWEEN 1 AND 99', name='ck_cp_passing'),
    sa.CheckConstraint('physic       BETWEEN 1 AND 99', name='ck_cp_physic'),
    sa.CheckConstraint('shirt_number BETWEEN 1 AND 99', name='ck_cp_shirt_number'),
    sa.CheckConstraint('shooting     BETWEEN 1 AND 99', name='ck_cp_shooting'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_one_dream_player_per_user')
    )
    op.create_index(op.f('ix_custom_players_id'), 'custom_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_players_id'), table_name='custom_players')
    op.drop_table('custom_players')
    # ### end Alembic commands ###
