"""Added club logo field to club table

Revision ID: 19afece82ddd
Revises: d677b23e3e18
Create Date: 2026-04-11 18:00:14.404472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19afece82ddd'
down_revision: Union[str, Sequence[str], None] = 'd677b23e3e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('logo_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_club_logo_url'), 'club', ['logo_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_logo_url'), table_name='club')
    op.drop_column('club', 'logo_url')
    # ### end Alembic commands ###
