"""add fields into club model

Revision ID: 1a1945443176
Revises: a173bac3fbc3
Create Date: 2026-03-14 16:09:14.636109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1945443176'
down_revision: Union[str, Sequence[str], None] = 'a173bac3fbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('name', sa.String(), nullable=True))
    op.add_column('club', sa.Column('league_name', sa.String(), nullable=True))
    op.add_column('club', sa.Column('nationality_name', sa.String(), nullable=True))
    op.add_column('club', sa.Column('overall', sa.Integer(), nullable=True))
    op.add_column('club', sa.Column('attack', sa.Integer(), nullable=True))
    op.add_column('club', sa.Column('midfield', sa.Integer(), nullable=True))
    op.add_column('club', sa.Column('defence', sa.Integer(), nullable=True))
    op.add_column('club', sa.Column('home_stadium', sa.String(), nullable=True))
    op.add_column('club', sa.Column('captain', sa.String(), nullable=True))
    op.create_index(op.f('ix_club_attack'), 'club', ['attack'], unique=False)
    op.create_index(op.f('ix_club_captain'), 'club', ['captain'], unique=False)
    op.create_index(op.f('ix_club_defence'), 'club', ['defence'], unique=False)
    op.create_index(op.f('ix_club_home_stadium'), 'club', ['home_stadium'], unique=False)
    op.create_index(op.f('ix_club_league_name'), 'club', ['league_name'], unique=False)
    op.create_index(op.f('ix_club_midfield'), 'club', ['midfield'], unique=False)
    op.create_index(op.f('ix_club_name'), 'club', ['name'], unique=False)
    op.create_index(op.f('ix_club_nationality_name'), 'club', ['nationality_name'], unique=False)
    op.create_index(op.f('ix_club_overall'), 'club', ['overall'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_overall'), table_name='club')
    op.drop_index(op.f('ix_club_nationality_name'), table_name='club')
    op.drop_index(op.f('ix_club_name'), table_name='club')
    op.drop_index(op.f('ix_club_midfield'), table_name='club')
    op.drop_index(op.f('ix_club_league_name'), table_name='club')
    op.drop_index(op.f('ix_club_home_stadium'), table_name='club')
    op.drop_index(op.f('ix_club_defence'), table_name='club')
    op.drop_index(op.f('ix_club_captain'), table_name='club')
    op.drop_index(op.f('ix_club_attack'), table_name='club')
    op.drop_column('club', 'captain')
    op.drop_column('club', 'home_stadium')
    op.drop_column('club', 'defence')
    op.drop_column('club', 'midfield')
    op.drop_column('club', 'attack')
    op.drop_column('club', 'overall')
    op.drop_column('club', 'nationality_name')
    op.drop_column('club', 'league_name')
    op.drop_column('club', 'name')
    # ### end Alembic commands ###
