"""create matches table

Revision ID: 1e37460be09c
Revises: 76cc47abcd30
Create Date: 2026-03-18 02:06:08.925196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e37460be09c'
down_revision: Union[str, Sequence[str], None] = '76cc47abcd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_prediction_id'), table_name='user_prediction')
    op.drop_index(op.f('ix_user_prediction_team1'), table_name='user_prediction')
    op.drop_index(op.f('ix_user_prediction_team2'), table_name='user_prediction')
    op.drop_index(op.f('ix_user_prediction_user_prediction'), table_name='user_prediction')
    op.drop_table('user_prediction')
    op.add_column('matches', sa.Column('round', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('matches', sa.Column('time', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('team1', sa.String(), nullable=False))
    op.add_column('matches', sa.Column('team2', sa.String(), nullable=False))
    op.add_column('matches', sa.Column('score_ft', sa.String(), nullable=True))
    op.drop_index(op.f('ix_matches_away_team'), table_name='matches')
    op.drop_index(op.f('ix_matches_competition'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team'), table_name='matches')
    op.drop_index(op.f('ix_matches_matchday'), table_name='matches')
    op.drop_index(op.f('ix_matches_season'), table_name='matches')
    op.drop_index(op.f('ix_matches_stage'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_utc_date'), table_name='matches')
    op.drop_column('matches', 'stage')
    op.drop_column('matches', 'away_score')
    op.drop_column('matches', 'home_team')
    op.drop_column('matches', 'home_score')
    op.drop_column('matches', 'season')
    op.drop_column('matches', 'competition')
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'matchday')
    op.drop_column('matches', 'away_team')
    op.drop_column('matches', 'utc_date')
    op.alter_column('matches', 'date', type_=sa.String(), existing_type=sa.DateTime(), postgresql_using='date::text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('utc_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('away_team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('matchday', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('competition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('home_team', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('matches', sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_matches_utc_date'), 'matches', ['utc_date'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_stage'), 'matches', ['stage'], unique=False)
    op.create_index(op.f('ix_matches_season'), 'matches', ['season'], unique=False)
    op.create_index(op.f('ix_matches_matchday'), 'matches', ['matchday'], unique=False)
    op.create_index(op.f('ix_matches_home_team'), 'matches', ['home_team'], unique=False)
    op.create_index(op.f('ix_matches_competition'), 'matches', ['competition'], unique=False)
    op.create_index(op.f('ix_matches_away_team'), 'matches', ['away_team'], unique=False)
    op.drop_column('matches', 'score_ft')
    op.drop_column('matches', 'team2')
    op.drop_column('matches', 'team1')
    op.drop_column('matches', 'time')
    op.drop_column('matches', 'date')
    op.drop_column('matches', 'round')
    op.create_table('user_prediction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_prediction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_prediction_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_prediction_pkey'))
    )
    op.create_index(op.f('ix_user_prediction_user_prediction'), 'user_prediction', ['user_prediction'], unique=False)
    op.create_index(op.f('ix_user_prediction_team2'), 'user_prediction', ['team2'], unique=False)
    op.create_index(op.f('ix_user_prediction_team1'), 'user_prediction', ['team1'], unique=False)
    op.create_index(op.f('ix_user_prediction_id'), 'user_prediction', ['id'], unique=False)
    # ### end Alembic commands ###
