"""Added_logo_in_leagueStandings

Revision ID: 1ecc89f4e034
Revises: d9c856a1cdf6
Create Date: 2026-04-20 02:33:21.824651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecc89f4e034'
down_revision: Union[str, Sequence[str], None] = 'd9c856a1cdf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_standings', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_standings', 'logo_url')
    # ### end Alembic commands ###
