"""added_bb_currency_and_unlock_system

Revision ID: 30800f13415d
Revises: 93fbe552157e
Create Date: 2026-05-01 23:01:46.140515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30800f13415d'
down_revision: Union[str, Sequence[str], None] = '93fbe552157e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unlocked_players', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unlocked_players', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_unlocked_players_id'), 'unlocked_players', ['id'], unique=False)
    op.create_foreign_key(None, 'unlocked_players', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'last_login_reward_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'last_chat_reward_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_chat_reward_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'last_login_reward_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'unlocked_players', type_='foreignkey')
    op.drop_index(op.f('ix_unlocked_players_id'), table_name='unlocked_players')
    op.alter_column('unlocked_players', 'unlocked_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('unlocked_players', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
