"""breaking down score into 2 columns

Revision ID: 42c96e70627d
Revises: b8390a899b75
Create Date: 2026-04-29 22:21:46.845019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c96e70627d'
down_revision: Union[str, Sequence[str], None] = 'b8390a899b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('team1_score', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('team2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'team2_score')
    op.drop_column('matches', 'team1_score')
    # ### end Alembic commands ###
