"""Added Match table

Revision ID: 4a561bec50c1
Revises: 76cc47abcd30
Create Date: 2026-03-18 16:11:38.228820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a561bec50c1'
down_revision: Union[str, Sequence[str], None] = '76cc47abcd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('team1', sa.String(), nullable=False),
    sa.Column('team2', sa.String(), nullable=False),
    sa.Column('score_ft', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
