"""removing captain column from club table

Revision ID: 6378dc7f1d4c
Revises: 920cd18dfe57
Create Date: 2026-04-29 21:15:07.149001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6378dc7f1d4c'
down_revision: Union[str, Sequence[str], None] = '920cd18dfe57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_club_captain'), table_name='club')
    op.drop_column('club', 'captain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('captain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_club_captain'), 'club', ['captain'], unique=False)
    # ### end Alembic commands ###
