"""Created DreamTeam and DreamTeamSlot tables

Revision ID: 6fee32ace2b7
Revises: d482a3845f75
Create Date: 2026-04-22 00:54:50.498324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fee32ace2b7'
down_revision: Union[str, Sequence[str], None] = 'd482a3845f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=20), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_dream_team_id'), 'dream_team', ['id'], unique=False)
    op.create_table('dream_team_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dream_team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dream_team_id'], ['dream_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_team_slot_id'), 'dream_team_slot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dream_team_slot_id'), table_name='dream_team_slot')
    op.drop_table('dream_team_slot')
    op.drop_index(op.f('ix_dream_team_id'), table_name='dream_team')
    op.drop_table('dream_team')
    # ### end Alembic commands ###
