"""Removing data columns from user table and removing created at column from unlocked player table

Revision ID: 819d18022a66
Revises: 30800f13415d
Create Date: 2026-05-02 00:16:32.735123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '819d18022a66'
down_revision: Union[str, Sequence[str], None] = '30800f13415d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unlocked_players', 'unlocked_at')
    op.drop_column('users', 'last_login_reward_at')
    op.drop_column('users', 'last_chat_reward_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_chat_reward_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login_reward_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('unlocked_players', sa.Column('unlocked_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
