"""add goalkeepers table

Revision ID: 98d9bbeacebf
Revises: bc387f0de81f
Create Date: 2026-03-19 22:55:12.196399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d9bbeacebf'
down_revision: Union[str, Sequence[str], None] = 'bc387f0de81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalkeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('long_name', sa.String(), nullable=True),
    sa.Column('player_positions', sa.String(), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('club_team_id', sa.Integer(), nullable=True),
    sa.Column('club_name', sa.String(), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('nationality_name', sa.String(), nullable=True),
    sa.Column('preferred_foot', sa.String(), nullable=True),
    sa.Column('weak_foot', sa.Integer(), nullable=True),
    sa.Column('skill_moves', sa.Integer(), nullable=True),
    sa.Column('work_rate', sa.String(), nullable=True),
    sa.Column('goalkeeping_diving', sa.Integer(), nullable=True),
    sa.Column('goalkeeping_handling', sa.Integer(), nullable=True),
    sa.Column('goalkeeping_kicking', sa.Integer(), nullable=True),
    sa.Column('goalkeeping_positioning', sa.Integer(), nullable=True),
    sa.Column('goalkeeping_reflexes', sa.Integer(), nullable=True),
    sa.Column('goalkeeping_speed', sa.Integer(), nullable=True),
    sa.Column('player_face_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['club_team_id'], ['club.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goalkeepers_age'), 'goalkeepers', ['age'], unique=False)
    op.create_index(op.f('ix_goalkeepers_club_name'), 'goalkeepers', ['club_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_dob'), 'goalkeepers', ['dob'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_diving'), 'goalkeepers', ['goalkeeping_diving'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_handling'), 'goalkeepers', ['goalkeeping_handling'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_kicking'), 'goalkeepers', ['goalkeeping_kicking'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_positioning'), 'goalkeepers', ['goalkeeping_positioning'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_reflexes'), 'goalkeepers', ['goalkeeping_reflexes'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_speed'), 'goalkeepers', ['goalkeeping_speed'], unique=False)
    op.create_index(op.f('ix_goalkeepers_height_cm'), 'goalkeepers', ['height_cm'], unique=False)
    op.create_index(op.f('ix_goalkeepers_id'), 'goalkeepers', ['id'], unique=False)
    op.create_index(op.f('ix_goalkeepers_long_name'), 'goalkeepers', ['long_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_nationality_id'), 'goalkeepers', ['nationality_id'], unique=False)
    op.create_index(op.f('ix_goalkeepers_nationality_name'), 'goalkeepers', ['nationality_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_overall'), 'goalkeepers', ['overall'], unique=False)
    op.create_index(op.f('ix_goalkeepers_player_face_url'), 'goalkeepers', ['player_face_url'], unique=False)
    op.create_index(op.f('ix_goalkeepers_player_positions'), 'goalkeepers', ['player_positions'], unique=False)
    op.create_index(op.f('ix_goalkeepers_preferred_foot'), 'goalkeepers', ['preferred_foot'], unique=False)
    op.create_index(op.f('ix_goalkeepers_short_name'), 'goalkeepers', ['short_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_skill_moves'), 'goalkeepers', ['skill_moves'], unique=False)
    op.create_index(op.f('ix_goalkeepers_weak_foot'), 'goalkeepers', ['weak_foot'], unique=False)
    op.create_index(op.f('ix_goalkeepers_weight_kg'), 'goalkeepers', ['weight_kg'], unique=False)
    op.create_index(op.f('ix_goalkeepers_work_rate'), 'goalkeepers', ['work_rate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goalkeepers_work_rate'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_weight_kg'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_weak_foot'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_skill_moves'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_short_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_preferred_foot'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_player_positions'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_player_face_url'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_overall'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_nationality_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_nationality_id'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_long_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_id'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_height_cm'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_speed'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_reflexes'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_positioning'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_kicking'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_handling'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_diving'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_dob'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_club_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_age'), table_name='goalkeepers')
    op.drop_table('goalkeepers')
    # ### end Alembic commands ###
