"""Added fixtures table

Revision ID: 9b633ed14d04
Revises: 98d9bbeacebf
Create Date: 2026-03-26 21:29:28.466087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b633ed14d04'
down_revision: Union[str, Sequence[str], None] = '98d9bbeacebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('away_team_score', sa.String(), nullable=True),
    sa.Column('home_team_score', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_id'), 'fixtures', ['id'], unique=False)
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coded_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leagues_pkey'))
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.drop_index(op.f('ix_fixtures_id'), table_name='fixtures')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
