"""update league table to club and update player to add more fields

Revision ID: a173bac3fbc3
Revises: fecea187fd37
Create Date: 2026-03-14 01:19:05.118625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a173bac3fbc3'
down_revision: Union[str, Sequence[str], None] = 'fecea187fd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_club_id'), 'club', ['id'], unique=False)
    op.drop_index(op.f('ix_leagues_country'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.drop_table('leagues')
    op.add_column('players', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('long_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('player_positions', sa.String(), nullable=True))
    op.add_column('players', sa.Column('overall', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('players', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('club_team_id', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('club_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('nationality_id', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('nationality_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('preferred_foot', sa.String(), nullable=True))
    op.add_column('players', sa.Column('weak_foot', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('skill_moves', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('work_rate', sa.String(), nullable=True))
    op.add_column('players', sa.Column('pace', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('shooting', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('passing', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('dribbling', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('defending', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('physic', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('player_face_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_players_country'), table_name='players')
    op.drop_index(op.f('ix_players_league'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.create_index(op.f('ix_players_age'), 'players', ['age'], unique=False)
    op.create_index(op.f('ix_players_club_name'), 'players', ['club_name'], unique=False)
    op.create_index(op.f('ix_players_defending'), 'players', ['defending'], unique=False)
    op.create_index(op.f('ix_players_dob'), 'players', ['dob'], unique=False)
    op.create_index(op.f('ix_players_dribbling'), 'players', ['dribbling'], unique=False)
    op.create_index(op.f('ix_players_height_cm'), 'players', ['height_cm'], unique=False)
    op.create_index(op.f('ix_players_long_name'), 'players', ['long_name'], unique=False)
    op.create_index(op.f('ix_players_nationality_id'), 'players', ['nationality_id'], unique=False)
    op.create_index(op.f('ix_players_nationality_name'), 'players', ['nationality_name'], unique=False)
    op.create_index(op.f('ix_players_overall'), 'players', ['overall'], unique=False)
    op.create_index(op.f('ix_players_pace'), 'players', ['pace'], unique=False)
    op.create_index(op.f('ix_players_passing'), 'players', ['passing'], unique=False)
    op.create_index(op.f('ix_players_physic'), 'players', ['physic'], unique=False)
    op.create_index(op.f('ix_players_player_face_url'), 'players', ['player_face_url'], unique=False)
    op.create_index(op.f('ix_players_player_positions'), 'players', ['player_positions'], unique=False)
    op.create_index(op.f('ix_players_preferred_foot'), 'players', ['preferred_foot'], unique=False)
    op.create_index(op.f('ix_players_shooting'), 'players', ['shooting'], unique=False)
    op.create_index(op.f('ix_players_short_name'), 'players', ['short_name'], unique=False)
    op.create_index(op.f('ix_players_skill_moves'), 'players', ['skill_moves'], unique=False)
    op.create_index(op.f('ix_players_weak_foot'), 'players', ['weak_foot'], unique=False)
    op.create_index(op.f('ix_players_weight_kg'), 'players', ['weight_kg'], unique=False)
    op.create_index(op.f('ix_players_work_rate'), 'players', ['work_rate'], unique=False)
    op.create_foreign_key(None, 'players', 'club', ['club_team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('players', 'country')
    op.drop_column('players', 'league')
    op.drop_column('players', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('league', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_index(op.f('ix_players_work_rate'), table_name='players')
    op.drop_index(op.f('ix_players_weight_kg'), table_name='players')
    op.drop_index(op.f('ix_players_weak_foot'), table_name='players')
    op.drop_index(op.f('ix_players_skill_moves'), table_name='players')
    op.drop_index(op.f('ix_players_short_name'), table_name='players')
    op.drop_index(op.f('ix_players_shooting'), table_name='players')
    op.drop_index(op.f('ix_players_preferred_foot'), table_name='players')
    op.drop_index(op.f('ix_players_player_positions'), table_name='players')
    op.drop_index(op.f('ix_players_player_face_url'), table_name='players')
    op.drop_index(op.f('ix_players_physic'), table_name='players')
    op.drop_index(op.f('ix_players_passing'), table_name='players')
    op.drop_index(op.f('ix_players_pace'), table_name='players')
    op.drop_index(op.f('ix_players_overall'), table_name='players')
    op.drop_index(op.f('ix_players_nationality_name'), table_name='players')
    op.drop_index(op.f('ix_players_nationality_id'), table_name='players')
    op.drop_index(op.f('ix_players_long_name'), table_name='players')
    op.drop_index(op.f('ix_players_height_cm'), table_name='players')
    op.drop_index(op.f('ix_players_dribbling'), table_name='players')
    op.drop_index(op.f('ix_players_dob'), table_name='players')
    op.drop_index(op.f('ix_players_defending'), table_name='players')
    op.drop_index(op.f('ix_players_club_name'), table_name='players')
    op.drop_index(op.f('ix_players_age'), table_name='players')
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_league'), 'players', ['league'], unique=False)
    op.create_index(op.f('ix_players_country'), 'players', ['country'], unique=False)
    op.drop_column('players', 'player_face_url')
    op.drop_column('players', 'physic')
    op.drop_column('players', 'defending')
    op.drop_column('players', 'dribbling')
    op.drop_column('players', 'passing')
    op.drop_column('players', 'shooting')
    op.drop_column('players', 'pace')
    op.drop_column('players', 'work_rate')
    op.drop_column('players', 'skill_moves')
    op.drop_column('players', 'weak_foot')
    op.drop_column('players', 'preferred_foot')
    op.drop_column('players', 'nationality_name')
    op.drop_column('players', 'nationality_id')
    op.drop_column('players', 'club_name')
    op.drop_column('players', 'club_team_id')
    op.drop_column('players', 'weight_kg')
    op.drop_column('players', 'height_cm')
    op.drop_column('players', 'dob')
    op.drop_column('players', 'age')
    op.drop_column('players', 'overall')
    op.drop_column('players', 'player_positions')
    op.drop_column('players', 'long_name')
    op.drop_column('players', 'short_name')
    op.create_table('leagues',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('leagues_pkey'))
    )
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=True)
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_country'), 'leagues', ['country'], unique=False)
    op.drop_index(op.f('ix_club_id'), table_name='club')
    op.drop_table('club')
    # ### end Alembic commands ###
