"""Removed goalkeepers table

Revision ID: afd18e45258c
Revises: ea684cc65505
Create Date: 2026-04-14 23:32:25.266126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afd18e45258c'
down_revision: Union[str, Sequence[str], None] = 'ea684cc65505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goalkeepers_age'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_club_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_dob'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_diving'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_handling'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_kicking'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_positioning'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_reflexes'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_goalkeeping_speed'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_height_cm'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_id'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_long_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_nationality_id'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_nationality_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_overall'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_player_face_url'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_player_positions'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_preferred_foot'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_short_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_skill_moves'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_weak_foot'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_weight_kg'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_work_rate'), table_name='goalkeepers')
    op.drop_table('goalkeepers')
    op.drop_index(op.f('ix_players_defending'), table_name='players')
    op.drop_index(op.f('ix_players_dribbling'), table_name='players')
    op.drop_index(op.f('ix_players_pace'), table_name='players')
    op.drop_index(op.f('ix_players_passing'), table_name='players')
    op.drop_index(op.f('ix_players_physic'), table_name='players')
    op.drop_index(op.f('ix_players_shooting'), table_name='players')
    op.drop_column('players', 'pace')
    op.drop_column('players', 'physic')
    op.drop_column('players', 'dribbling')
    op.drop_column('players', 'passing')
    op.drop_column('players', 'shooting')
    op.drop_column('players', 'defending')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('defending', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('shooting', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('passing', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('dribbling', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('physic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('pace', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_players_shooting'), 'players', ['shooting'], unique=False)
    op.create_index(op.f('ix_players_physic'), 'players', ['physic'], unique=False)
    op.create_index(op.f('ix_players_passing'), 'players', ['passing'], unique=False)
    op.create_index(op.f('ix_players_pace'), 'players', ['pace'], unique=False)
    op.create_index(op.f('ix_players_dribbling'), 'players', ['dribbling'], unique=False)
    op.create_index(op.f('ix_players_defending'), 'players', ['defending'], unique=False)
    op.create_table('goalkeepers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('player_positions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dob', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('club_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('club_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nationality_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nationality_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preferred_foot', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weak_foot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill_moves', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_rate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goalkeeping_diving', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeping_handling', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeping_kicking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeping_positioning', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeping_reflexes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goalkeeping_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_face_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['club_team_id'], ['club.id'], name=op.f('goalkeepers_club_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('goalkeepers_pkey'))
    )
    op.create_index(op.f('ix_goalkeepers_work_rate'), 'goalkeepers', ['work_rate'], unique=False)
    op.create_index(op.f('ix_goalkeepers_weight_kg'), 'goalkeepers', ['weight_kg'], unique=False)
    op.create_index(op.f('ix_goalkeepers_weak_foot'), 'goalkeepers', ['weak_foot'], unique=False)
    op.create_index(op.f('ix_goalkeepers_skill_moves'), 'goalkeepers', ['skill_moves'], unique=False)
    op.create_index(op.f('ix_goalkeepers_short_name'), 'goalkeepers', ['short_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_preferred_foot'), 'goalkeepers', ['preferred_foot'], unique=False)
    op.create_index(op.f('ix_goalkeepers_player_positions'), 'goalkeepers', ['player_positions'], unique=False)
    op.create_index(op.f('ix_goalkeepers_player_face_url'), 'goalkeepers', ['player_face_url'], unique=False)
    op.create_index(op.f('ix_goalkeepers_overall'), 'goalkeepers', ['overall'], unique=False)
    op.create_index(op.f('ix_goalkeepers_nationality_name'), 'goalkeepers', ['nationality_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_nationality_id'), 'goalkeepers', ['nationality_id'], unique=False)
    op.create_index(op.f('ix_goalkeepers_long_name'), 'goalkeepers', ['long_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_id'), 'goalkeepers', ['id'], unique=False)
    op.create_index(op.f('ix_goalkeepers_height_cm'), 'goalkeepers', ['height_cm'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_speed'), 'goalkeepers', ['goalkeeping_speed'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_reflexes'), 'goalkeepers', ['goalkeeping_reflexes'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_positioning'), 'goalkeepers', ['goalkeeping_positioning'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_kicking'), 'goalkeepers', ['goalkeeping_kicking'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_handling'), 'goalkeepers', ['goalkeeping_handling'], unique=False)
    op.create_index(op.f('ix_goalkeepers_goalkeeping_diving'), 'goalkeepers', ['goalkeeping_diving'], unique=False)
    op.create_index(op.f('ix_goalkeepers_dob'), 'goalkeepers', ['dob'], unique=False)
    op.create_index(op.f('ix_goalkeepers_club_name'), 'goalkeepers', ['club_name'], unique=False)
    op.create_index(op.f('ix_goalkeepers_age'), 'goalkeepers', ['age'], unique=False)
    # ### end Alembic commands ###
