"""removing nationality id and club name column from player table

Revision ID: b8390a899b75
Revises: 6378dc7f1d4c
Create Date: 2026-04-29 21:51:46.107973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8390a899b75'
down_revision: Union[str, Sequence[str], None] = '6378dc7f1d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_club_name'), table_name='players')
    op.drop_index(op.f('ix_players_nationality_id'), table_name='players')
    op.drop_column('players', 'nationality_id')
    op.drop_column('players', 'club_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('club_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('nationality_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_players_nationality_id'), 'players', ['nationality_id'], unique=False)
    op.create_index(op.f('ix_players_club_name'), 'players', ['club_name'], unique=False)
    # ### end Alembic commands ###
