"""

Revision ID: ca79d3dea5e0
Revises: 1ecc89f4e034
Create Date: 2026-04-21 17:34:20.612279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca79d3dea5e0'
down_revision: Union[str, Sequence[str], None] = '1ecc89f4e034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_standings', sa.Column('form', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_standings', 'form')
    # ### end Alembic commands ###
