"""Adding Form table

Revision ID: d482a3845f75
Revises: 1ecc89f4e034
Create Date: 2026-04-22 00:09:44.068348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd482a3845f75'
down_revision: Union[str, Sequence[str], None] = '1ecc89f4e034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_standing_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_standing_id'], ['league_standings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
