"""Added custom players table

Revision ID: d677b23e3e18
Revises: 89894c529cf9
Create Date: 2026-04-10 16:37:23.978742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd677b23e3e18'
down_revision: Union[str, Sequence[str], None] = '89894c529cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=False),
    sa.Column('preferred_foot', sa.String(length=5), nullable=False),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('shooting', sa.Integer(), nullable=False),
    sa.Column('passing', sa.Integer(), nullable=False),
    sa.Column('dribbling', sa.Integer(), nullable=False),
    sa.Column('defending', sa.Integer(), nullable=False),
    sa.Column('physic', sa.Integer(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_custom_players_id'), 'custom_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_players_id'), table_name='custom_players')
    op.drop_table('custom_players')
    # ### end Alembic commands ###
