"""Remove player_positions from players

Revision ID: d9c856a1cdf6
Revises: 1b118417a21e
Create Date: 2026-04-19 00:48:08.604941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c856a1cdf6'
down_revision: Union[str, Sequence[str], None] = '1b118417a21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_player_positions'), table_name='players')
    op.drop_column('players', 'player_positions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('player_positions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_players_player_positions'), 'players', ['player_positions'], unique=False)
    # ### end Alembic commands ###
