"""removing score_ft column from matches table

Revision ID: dd7e868cb693
Revises: 42c96e70627d
Create Date: 2026-04-29 22:29:10.361570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7e868cb693'
down_revision: Union[str, Sequence[str], None] = '42c96e70627d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'score_ft')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('score_ft', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
