"""Updated User Table (added created_at and super_user fields)

Revision ID: e83d72bdd566
Revises: 3a195dd54ef0
Create Date: 2026-03-11 00:45:18.416350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83d72bdd566'
down_revision: Union[str, Sequence[str], None] = '3a195dd54ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('super_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'super_user')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
