"""Added player stats and goalkeeper stats table

Revision ID: ea684cc65505
Revises: 19afece82ddd
Create Date: 2026-04-14 20:09:08.830592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea684cc65505'
down_revision: Union[str, Sequence[str], None] = '19afece82ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalkeeper_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('diving', sa.Integer(), nullable=True),
    sa.Column('handling', sa.Integer(), nullable=True),
    sa.Column('kicking', sa.Integer(), nullable=True),
    sa.Column('positioning', sa.Integer(), nullable=True),
    sa.Column('reflexes', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_goalkeeper_stats_id'), 'goalkeeper_stats', ['id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('pace', sa.Integer(), nullable=True),
    sa.Column('shooting', sa.Integer(), nullable=True),
    sa.Column('passing', sa.Integer(), nullable=True),
    sa.Column('dribbling', sa.Integer(), nullable=True),
    sa.Column('defending', sa.Integer(), nullable=True),
    sa.Column('physic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_goalkeeper_stats_id'), table_name='goalkeeper_stats')
    op.drop_table('goalkeeper_stats')
    # ### end Alembic commands ###
